#!/usr/bin/env node
/* ---------------------------------------------------------------------
   auth-set — configure Personal Hub secrets in .env.local.

   Usage:
     npm run auth:set                 ← prompts for each secret (RECOMMENDED)
     npm run auth:set -- --master '<password>' [--budget '<code>'] [--health '<code>']

   Prefer the prompt. Passing secrets as arguments has two problems on
   Windows: PowerShell mangles unquoted values containing `$`, `&`, spaces
   or `!` (silently storing a different password, or refusing to run), and
   whatever you type lands in your shell history. The prompt avoids both —
   input is hidden and never reaches the command line.

   - Generates SESSION_SECRET + ENCRYPTION_KEY once, then PRESERVES them on
     re-run (rotating ENCRYPTION_KEY would make existing encrypted data
     unreadable — pass --rotate-keys to force, only on an empty/disposable db).
   - argon2-hashes each provided secret and writes the hash (never the
     plaintext) to .env.local. Other keys in the file (e.g. WEATHER_*) are
     preserved.
   --------------------------------------------------------------------- */
import { hash } from "@node-rs/argon2";
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import readline from "node:readline";

const ENV_PATH = path.join(process.cwd(), ".env.local");

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      if (key === "rotate-keys") out[key] = true;
      else out[key] = argv[++i];
    }
  }
  return out;
}

function readEnv() {
  const map = new Map();
  if (existsSync(ENV_PATH)) {
    for (const line of readFileSync(ENV_PATH, "utf8").split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (!m) continue;
      let val = m[2];
      // Strip surrounding quotes we (or the user) may have added.
      if (
        (val.startsWith("'") && val.endsWith("'")) ||
        (val.startsWith('"') && val.endsWith('"'))
      ) {
        val = val.slice(1, -1);
      }
      map.set(m[1], val);
    }
  }
  return map;
}

function writeEnv(map) {
  const header =
    "# Personal Hub secrets — generated by `npm run auth:set`. NEVER commit.\n";
  const body = [...map.entries()].map(([k, v]) => `${k}=${v}`).join("\n");
  writeFileSync(ENV_PATH, header + body + "\n", { mode: 0o600 });
}

/* Ask for each secret without echoing it. One shared readline interface —
   opening a fresh one per question leaves the later ones hanging once the
   first has consumed the stream. Works interactively (typing hidden) and
   from a pipe, so it stays scriptable and testable. */
const BANNER =
  "Enter each secret, or press Enter to leave it unchanged.\n" +
  "Typing is hidden and nothing is written to your shell history.\n";

/* Piped stdin (scripts, tests): consume it whole and take one line per
   field. readline misbehaves across successive questions on a pipe, so
   this path deliberately avoids it. */
async function promptPiped() {
  let data = "";
  for await (const chunk of process.stdin) data += chunk;
  const [master = "", budget = "", health = ""] = data.split(/\r?\n/);
  return { master: master.trim(), budget: budget.trim(), health: health.trim() };
}

/* Interactive terminal: one readline interface, echo suppressed while the
   secret is typed. */
async function promptTTY() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: true,
  });
  let muted = false;
  rl._writeToOutput = (s) => {
    if (!muted) process.stdout.write(s);
  };

  const ask = (label) =>
    new Promise((resolve) => {
      process.stdout.write(label);
      muted = true;
      rl.question("", (answer) => {
        muted = false;
        process.stdout.write("\n");
        resolve(answer.trim());
      });
    });

  console.log(BANNER);
  const master = await ask("Master password : ");
  const budget = await ask("Budget passcode : ");
  const health = await ask("Health passcode : ");
  rl.close();
  return { master, budget, health };
}

async function promptAll() {
  if (process.stdin.isTTY) return promptTTY();
  return promptPiped();
}

const args = parseArgs(process.argv.slice(2));
const env = readEnv();
const changed = [];

/* No credential flags given → ask interactively. This is the recommended
   path: it sidesteps shell quoting entirely. */
const gaveFlags = args.master || args.budget || args.health;
const prompted =
  !gaveFlags && !args["rotate-keys"] && !process.env.MASTER_PASSWORD
    ? await promptAll()
    : {};

// Keys: generate once, preserve thereafter (unless --rotate-keys).
for (const key of ["SESSION_SECRET", "ENCRYPTION_KEY"]) {
  if (!env.has(key) || args["rotate-keys"]) {
    env.set(key, randomBytes(32).toString("hex"));
    changed.push(env.has(key) && !args["rotate-keys"] ? key : `${key} (generated)`);
  }
}

// Credential hashes from args (or env fallbacks for non-interactive use).
const creds = [
  [
    "MASTER_PASSWORD_HASH",
    args.master ?? prompted.master ?? process.env.MASTER_PASSWORD,
  ],
  [
    "BUDGET_PASSCODE_HASH",
    args.budget ?? prompted.budget ?? process.env.BUDGET_PASSCODE,
  ],
  [
    "HEALTH_PASSCODE_HASH",
    args.health ?? prompted.health ?? process.env.HEALTH_PASSCODE,
  ],
];
for (const [envKey, plaintext] of creds) {
  if (plaintext) {
    // Store base64(argon2 hash): the raw hash contains `$`, which the dotenv
    // loader treats as variable expansion and corrupts. base64 has no `$`.
    const h = await hash(String(plaintext));
    env.set(envKey, Buffer.from(h, "utf8").toString("base64"));
    changed.push(envKey);
  }
}

writeEnv(env);

if (changed.length === 0) {
  console.log("Nothing changed.");
} else {
  console.log("Updated .env.local:");
  for (const c of changed) console.log("  ·", c);
  console.log("(plaintext secrets were hashed and never written to disk)");
}
